name: CI
on: workflow_dispatch

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v3

  #     - name: Test
  #       run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build
        run: ./gradlew build
        
      - name: Build
        run: tree

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: jar-files
          path: build
