name: CI
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/build
          key: gradle-files

      - name: Test
        run: ./gradlew test


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/build
          key: gradle-files
          
      - name: Build
        run: ./gradlew build
        
      - name: Build
        run: tree

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with: 
          name: jar-files
        
      - name: Deploy
        run: ./gradlew build
