name: CI
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache workspace
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-workspace-

      - name: Test
        run: ./gradlew test


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache workspace 
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-workspace-

      - name: Build
        run: ./gradlew build
        
      - name: Build
        run: tree

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-files

      - name: Cache workspace 
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-workspace-${{ hashFiles('**/*') }}
          restore-keys: |
            ${{ runner.os }}-workspace-
        
      - name: Deploy
        run: tree
